export const DASHBOARD_PLATFORMS = ['shopify', 'amazon', 'mercadolibre'] as const

export type DashboardSalesChannel = (typeof DASHBOARD_PLATFORMS)[number]

export const PLATFORM_LABELS: Record<DashboardSalesChannel, string> = {
  shopify: 'Shopify',
  amazon: 'Amazon',
  mercadolibre: 'Mercado Libre',
}

export const COLORS_BY_CHANNEL: Record<DashboardSalesChannel, string> = {
  shopify: '#5B8CFF',
  amazon: '#9B8CE8',
  mercadolibre: '#5A9F7A',
}

const STRINGS = {
  es: {
    pageTitle: 'Ventas',
    pageDesc: 'Analítica de ingresos y KPIs',
    salesPageDesc: 'Analisis de ventas por canal y periodo',

    filterStart: 'Fecha inicio',
    filterEnd: 'Fecha fin',
    filterTo: 'a',
    shortcutYear: 'Año',
    shortcutYearPlaceholder: 'Año…',
    shortcutMonth: 'Mes',
    channels: 'Canales',
    channelsAll: 'Todos los canales',
    searchChannels: 'Buscar canal…',
    filterProduct: 'Producto',
    allProducts: 'Todos los productos',
    searchProducts: 'Buscar producto…',
    noProducts: 'Sin productos',
    productsPickedCount: '{{n}} productos',

    granularityDaily: 'Diario',
    granularityWeekly: 'Semanal',
    granularityMonthly: 'Mensual',

    sectionOverview: 'Resumen',
    sectionProfitability: 'Rentabilidad',
    sectionTrends: 'Tendencias',
    filterMoreOptions: 'Más opciones',
    filterSecondaryTitle: 'Periodo y granularidad',
    filterGranularity: 'Granularidad',

    kpiGross: 'Ventas brutas',
    kpiNet: 'Ventas netas',
    kpiGrossProfit: 'Utilidad bruta',
    kpiMargin: 'Margen',
    kpiReceived: 'Total recibido',

    deltaVsPrev: 'vs periodo anterior',
    deltaVsPrevMonth: 'vs mes anterior',

    wfTitle: 'Cascada P&L',
    donutTitle: 'Participación de ventas por canal',
    monthlyTitle: 'Evolución Mensual — Ingresos · Utilidad · EBITDA · Margen',
    costTitle: 'Estructura de costos por canal y categoría',
    overlayTitle: 'Ventas brutas y netas por canal',
    overlayVisibilityMenu: 'Mostrar',
    overlayVisibilityTitle: 'Visibilidad del gráfico',
    overlayVisibilityGrossNet: 'Leyenda opacidad (brutas / netas)',
    overlayVisibilityChannels: 'Canales',
    overlayMonthlyHint: 'Agregación mensual por canal (más legible que el detalle diario).',
    marginTitle: 'Margen % por Canal',

    traceGrossRevenue: 'Ventas brutas',
    traceNetRevenue: 'Ventas netas',
    traceGrossProfit: 'Utilidad bruta',
    traceCostOfSalesTotal: 'Costo de ventas (total)',
    traceCostOfSalesOther: 'Otros costos de ventas',
    tracePnlReconcile: 'Otros ajustes a utilidad bruta',
    wfReconcileFootnote:
      '“Otros ajustes…” aparece solo si la utilidad bruta del archivo no coincide exactamente con ventas netas menos costo de ventas total (redondeo u otras partidas en el origen).',
    traceEbitda: 'EBITDA',
    traceMarginPct: 'Margen %',

    monthlyChartNetIngresos: 'Ventas netas (Ingresos)',
    monthlyChartMarginLine: 'Margen %',

    costCogs: 'COGS',
    costCommission: 'Comisiones',
    costShipping: 'Envios',
    costAds: 'Ads',
    costPlatformVariable: 'Costos variables canal',
    traceContributionMargin: 'Contribucion marginal',

    modalTitle: 'Desglose por canal',
    modalPeriod: 'Periodo',
    modalChannel: 'Canal',
    modalGross: 'Ventas brutas',
    modalNet: 'Ventas netas',
    modalCogs: 'COGS',
    modalCommission: 'Comisiones',
    modalShipping: 'Envios',
    modalAds: 'Ads',
    modalGrossProfit: 'Utilidad bruta',
    salesUtilityMarginTitle: 'Utilidad Bruta + Margen %',
    utilityDrilldownTopProductsTitle: 'Top Productos',
    chartViewGrouped: 'Agrupadas',
    chartViewStacked: 'Apiladas',
    salesMomTitle: 'Crecimiento MoM (Ventas Netas)',
    salesByBrandTitle: 'Ventas por Marca',
    salesDetailedTableTitle: 'Tabla Detallada',
    salesTablePeriod: 'Periodo',
    salesTableOrders: 'Pedidos',

    legendGross: 'Ventas brutas (menos opacidad)',
    legendNet: 'Ventas netas (más opacidad)',
    reportsPageTitle: 'Reportes',
    reportsPageDesc: 'Estado de resultados y rentabilidad consolidada',
    reportsOperatingExpenses: 'Gastos operativos',
    reportsStatementTitle: 'Estado de resultados consolidado',
    reportsByChannelTitle: 'Desglose por canal',
    reportsSalesMixTitle: 'Mix ventas por canal',
    reportsExpensesByCategoryTitle: 'Gastos por categoria',
    reportsEbitdaMargin: 'Margen EBITDA %',

    productsPageTitle: 'Productos',
    productsTopTitle: 'Top 15 Productos',
    productsTopSubtitle: 'Ventas totales apiladas por canal',
    productsTopMarginTitle: 'Top 5 mayor margen',
    productsBottomMarginTitle: 'Top 5 menor margen',
    productsHeatmapTitle: 'Mapa de calor: Producto x Canal',
    productsSkuTableTitle: 'Detalle por SKU',
    productsCostEditorTitle: 'Editor de costos unitarios',
    productsSaveCosts: 'Guardar cambios',
    productsResetCosts: 'Restaurar originales',
    productsMargin: 'Margen %',
    productsRevenue: 'Ventas',
    productsUnits: 'Unidades',
    productsCogs: 'COGS',
    productsTableProduct: 'Producto',
    productsTableSku: 'SKU',
    productsTableCostCurrent: 'Costo actual',
    productsTableCostOriginal: 'Costo original',
    productsTableDeltaCogs: 'Delta COGS',
    productsNoData: 'Sin datos',
    productsFilterSkuPlaceholder: 'Filtrar por producto o SKU',
    productsFilterCostPlaceholder: 'Filtrar editor de costos por producto',
    tableColumns: 'Columnas',
    tablePage: 'Página',
    tableRows: 'filas',
    tablePrev: 'Anterior',
    tableNext: 'Siguiente',
    tableGoTo: 'Ir a',
    tableGo: 'Ir',
    tableToggleColumns: 'Mostrar/ocultar columnas',
    tableLoadingPage: 'Cargando página...',
    tableSelectAllColumns: 'Seleccionar todas',
    tableDeselectAllColumns: 'Deseleccionar todas',
    tableClearSearch: 'Limpiar búsqueda',
    productsEmptyErrorTitle: 'No se pudieron cargar los datos de productos',
    productsEmptyErrorDescription:
      'Hubo un error al obtener los datos de productos. Intenta de nuevo y, si persiste, revisa la sesión/autenticación del API.',
    productsEmptyNoDataDescription:
      'No hay productos para los filtros actuales. Prueba ampliar el rango de fechas, cambiar canales o limpiar filtros.',
    productsEmptyRetry: 'Reintentar',
    productsEmptyResetFilters: 'Restablecer filtros',

    catalogTabList: 'Catálogo',
    catalogTabUnmapped: 'Sin mapear',
    catalogPageDesc: 'Catálogo central y líneas de venta sin producto asignado.',
    catalogSearchPlaceholder: 'Buscar productos, SKU o marca…',
    catalogColBrand: 'Marca',
    catalogColListings: 'Publicaciones',
    catalogColActive: 'Activo',
    catalogYes: 'Sí',
    catalogNo: 'No',
    productStatusActive: 'Activo',
    productStatusInactive: 'Inactivo',
    catalogDetailListings: 'Publicaciones por canal',
    catalogDetailKpis: 'Rendimiento',
    catalogDetailLoading: 'Cargando producto…',
    catalogNotFound: 'Producto no encontrado',
    unmappedTitle: 'Líneas sin mapear',
    unmappedDesc: 'Agrupadas por canal, SKU y título en el periodo.',
    unmappedColPlatform: 'Canal',
    unmappedColSku: 'SKU (clave)',
    unmappedColTitle: 'Título en la venta',
    unmappedColRevenue: 'Ventas',
    unmappedColLines: 'Líneas',
    unmappedAssign: 'Asignar',
    catalogAssignDialogTitle: 'Asignar a producto del catálogo',
    catalogAssignPickProduct: 'Producto',
    catalogAssignPlatformSkuLabel: 'SKU en la plataforma',
    catalogAssignConfirm: 'Guardar',
    catalogAdminOnly: 'Solo administradores pueden asignar.',
    catalogEmptyList: 'No hay productos en el catálogo.',
    catalogImageUrlLabel: 'URL de imagen',
    catalogSaveImage: 'Guardar imagen',
    catalogImageUploadTitle: 'Imagen del producto',
    catalogImageUploadCta: 'Haz clic o arrastra una imagen',
    catalogImageUploadHint: 'La subida a la nube (S3) estará disponible pronto.',
    catalogImageFileSelected: 'Archivo seleccionado',
    catalogProductTrend: 'Tendencia de ventas netas',
    catalogTrendEmptyTitle: 'Sin datos de tendencia',
    catalogTrendEmptyDesc: 'Prueba otro periodo o conecta canales para ver la evolución de ventas netas.',
    catalogPerfEmptyTitle: 'Sin datos de rendimiento',
    catalogPerfEmptyDesc: 'Conecta canales para ver ventas y márgenes por producto en este periodo.',
    productStatChannels: 'Canales',
    productsChannelSelloutPrice: 'Precio de venta (unitario)',
    productsChannelCost: 'COGS (periodo)',
    productsChannelFees: 'Comisiones',
    productHeroMeta: '{c} canales · {l} publicaciones',
    unmappedEmpty: 'No hay líneas sin mapear en este periodo.',
    catalogSelectPlaceholder: 'Selecciona un producto…',
    catalogEmptySkuNote:
      'La línea no tiene SKU: indica el SKU de la publicación en la plataforma.',
    catalogDialogClose: 'Cerrar',

    productScopeBanner:
      'Vista por producto: los anuncios no se asignan por SKU; la cascada termina en utilidad bruta. Comisiones y envío se prorratean por participación de la línea en el subtotal del pedido.',
  },
  en: {
    pageTitle: 'Sales',
    pageDesc: 'Revenue analytics and KPIs',
    salesPageDesc: 'Sales analysis by channel and period',

    filterStart: 'Start date',
    filterEnd: 'End date',
    filterTo: 'to',
    shortcutYear: 'Year',
    shortcutYearPlaceholder: 'Year…',
    shortcutMonth: 'Month',
    channels: 'Channels',
    channelsAll: 'All channels',
    searchChannels: 'Search channel…',
    filterProduct: 'Product',
    allProducts: 'All products',
    searchProducts: 'Search product…',
    noProducts: 'No products',
    productsPickedCount: '{{n}} products',

    granularityDaily: 'Daily',
    granularityWeekly: 'Weekly',
    granularityMonthly: 'Monthly',

    sectionOverview: 'Overview',
    sectionProfitability: 'Profitability',
    sectionTrends: 'Trends',
    filterMoreOptions: 'More options',
    filterSecondaryTitle: 'Period & granularity',
    filterGranularity: 'Granularity',

    kpiGross: 'Gross sales',
    kpiNet: 'Net sales',
    kpiGrossProfit: 'Gross profit',
    kpiMargin: 'Margin',
    kpiReceived: 'Total received',

    deltaVsPrev: 'vs prior period',
    deltaVsPrevMonth: 'vs prior month',

    wfTitle: 'P&L waterfall',
    donutTitle: 'Share of net sales by channel',
    monthlyTitle: 'Monthly evolution — Revenue · Profit · EBITDA · Margin',
    costTitle: 'Cost structure by channel and category',
    overlayTitle: 'Gross and net sales by channel',
    overlayVisibilityMenu: 'Show',
    overlayVisibilityTitle: 'Chart visibility',
    overlayVisibilityGrossNet: 'Opacity legend (gross / net)',
    overlayVisibilityChannels: 'Channels',
    overlayMonthlyHint: 'Monthly totals per channel (easier to read than daily detail).',
    marginTitle: 'Margin % by channel',

    traceGrossRevenue: 'Gross revenue',
    traceNetRevenue: 'Net revenue',
    traceGrossProfit: 'Gross profit',
    traceCostOfSalesTotal: 'Cost of sales (total)',
    traceCostOfSalesOther: 'Other cost of sales',
    tracePnlReconcile: 'Other adjustments to gross profit',
    wfReconcileFootnote:
      '“Other adjustments…” only appears when reported gross profit does not exactly equal net sales minus total cost of sales (rounding or extra lines in the source data).',
    traceEbitda: 'EBITDA',
    traceMarginPct: 'Margin %',

    monthlyChartNetIngresos: 'Net sales (revenue)',
    monthlyChartMarginLine: 'Margin %',

    costCogs: 'COGS',
    costCommission: 'Commissions',
    costShipping: 'Shipping',
    costAds: 'Ads',
    costPlatformVariable: 'Platform variable costs',
    traceContributionMargin: 'Contribution margin',

    modalTitle: 'Breakdown by channel',
    modalPeriod: 'Period',
    modalChannel: 'Channel',
    modalGross: 'Gross sales',
    modalNet: 'Net sales',
    modalCogs: 'COGS',
    modalCommission: 'Commissions',
    modalShipping: 'Shipping',
    modalAds: 'Ads',
    modalGrossProfit: 'Gross profit',
    salesUtilityMarginTitle: 'Gross Profit + Margin %',
    utilityDrilldownTopProductsTitle: 'Top Products',
    chartViewGrouped: 'Grouped',
    chartViewStacked: 'Stacked',
    salesMomTitle: 'MoM Growth (Net Sales)',
    salesByBrandTitle: 'Sales by Brand',
    salesDetailedTableTitle: 'Detailed Table',
    salesTablePeriod: 'Period',
    salesTableOrders: 'Orders',

    legendGross: 'Gross (lower opacity)',
    legendNet: 'Net (higher opacity)',
    reportsPageTitle: 'Reports',
    reportsPageDesc: 'Consolidated statement and profitability',
    reportsOperatingExpenses: 'Operating expenses',
    reportsStatementTitle: 'Consolidated statement',
    reportsByChannelTitle: 'Breakdown by channel',
    reportsSalesMixTitle: 'Sales mix by channel',
    reportsExpensesByCategoryTitle: 'Expenses by category',
    reportsEbitdaMargin: 'EBITDA Margin %',

    productsPageTitle: 'Products',
    productsTopTitle: 'Top 15 Products',
    productsTopSubtitle: 'Total sales stacked by channel',
    productsTopMarginTitle: 'Top 5 highest margin',
    productsBottomMarginTitle: 'Top 5 lowest margin',
    productsHeatmapTitle: 'Heatmap: Product x Channel',
    productsSkuTableTitle: 'SKU Detail',
    productsCostEditorTitle: 'Unit Cost Editor',
    productsSaveCosts: 'Save changes',
    productsResetCosts: 'Restore original',
    productsMargin: 'Margin %',
    productsRevenue: 'Revenue',
    productsUnits: 'Units',
    productsCogs: 'COGS',
    productsTableProduct: 'Product',
    productsTableSku: 'SKU',
    productsTableCostCurrent: 'Current cost',
    productsTableCostOriginal: 'Original cost',
    productsTableDeltaCogs: 'COGS delta',
    productsNoData: 'No data',
    productsFilterSkuPlaceholder: 'Filter by product or SKU',
    productsFilterCostPlaceholder: 'Filter cost editor by product',
    tableColumns: 'Columns',
    tablePage: 'Page',
    tableRows: 'rows',
    tablePrev: 'Prev',
    tableNext: 'Next',
    tableGoTo: 'Go to',
    tableGo: 'Go',
    tableToggleColumns: 'Toggle columns',
    tableLoadingPage: 'Loading page...',
    tableSelectAllColumns: 'Select all',
    tableDeselectAllColumns: 'Deselect all',
    tableClearSearch: 'Clear search',
    productsEmptyErrorTitle: 'Could not load products data',
    productsEmptyErrorDescription:
      'There was an error fetching products data. Please retry, and if it persists, check API auth/session.',
    productsEmptyNoDataDescription:
      'No products matched your current filters. Try widening the date range, changing channels, or clearing filters.',
    productsEmptyRetry: 'Retry',
    productsEmptyResetFilters: 'Reset filters',

    catalogTabList: 'Catalog',
    catalogTabUnmapped: 'Unmapped',
    catalogPageDesc: 'Central catalog and sale lines without an assigned product.',
    catalogSearchPlaceholder: 'Search products, SKU or brand…',
    catalogColBrand: 'Brand',
    catalogColListings: 'Listings',
    catalogColActive: 'Active',
    catalogYes: 'Yes',
    catalogNo: 'No',
    productStatusActive: 'Active',
    productStatusInactive: 'Inactive',
    catalogDetailListings: 'Listings by channel',
    catalogDetailKpis: 'Performance',
    catalogDetailLoading: 'Loading product…',
    catalogNotFound: 'Product not found',
    unmappedTitle: 'Unmapped lines',
    unmappedDesc: 'Grouped by channel, SKU, and line title in the period.',
    unmappedColPlatform: 'Channel',
    unmappedColSku: 'SKU (key)',
    unmappedColTitle: 'Line title',
    unmappedColRevenue: 'Revenue',
    unmappedColLines: 'Lines',
    unmappedAssign: 'Assign',
    catalogAssignDialogTitle: 'Assign to catalog product',
    catalogAssignPickProduct: 'Product',
    catalogAssignPlatformSkuLabel: 'Platform SKU',
    catalogAssignConfirm: 'Save',
    catalogAdminOnly: 'Only workspace admins can assign.',
    catalogEmptyList: 'No products in the catalog.',
    catalogImageUrlLabel: 'Image URL',
    catalogSaveImage: 'Save image',
    catalogImageUploadTitle: 'Product image',
    catalogImageUploadCta: 'Click or drag an image',
    catalogImageUploadHint: 'Cloud upload (S3) will be available soon.',
    catalogImageFileSelected: 'Selected file',
    catalogProductTrend: 'Net sales trend',
    catalogTrendEmptyTitle: 'No trend data yet',
    catalogTrendEmptyDesc: 'Try another date range or connect channels to see net sales over time.',
    catalogPerfEmptyTitle: 'No performance data yet',
    catalogPerfEmptyDesc: 'Connect channels to see sales performance and margins for this product.',
    productStatChannels: 'Channels',
    productsChannelSelloutPrice: 'Unit sellout price',
    productsChannelCost: 'COGS (period)',
    productsChannelFees: 'Fees',
    productHeroMeta: '{c} channels · {l} listings',
    unmappedEmpty: 'No unmapped lines in this period.',
    catalogSelectPlaceholder: 'Select a product…',
    catalogEmptySkuNote: 'This line has no SKU: enter the listing SKU for the platform.',
    catalogDialogClose: 'Close',

    productScopeBanner:
      'Product view: ad spend is not allocated to SKUs; the waterfall ends at gross profit. Commission and shipping are prorated by line share of order subtotal.',
  },
} as const

export type DashboardStringKey = keyof typeof STRINGS.es

export function dashboardT(lang: string, key: DashboardStringKey): string {
  const locale = lang === 'en' ? 'en' : 'es'
  const table = STRINGS[locale]
  return table[key] ?? key
}
