import type { AssignablePermissionKey } from '@/lib/permissions/can'
import type { ShellStringKey } from '@/lib/i18n/shell-strings'

export const PERMISSION_LABEL_KEYS: Record<AssignablePermissionKey, ShellStringKey> = {
  'ads.view': 'permAdsView',
  'alerts.manage': 'permAlertsManage',
  'alerts.view': 'permAlertsView',
  'channels.view': 'permChannelsView',
  'expenses.create': 'permExpensesCreate',
  'expenses.delete': 'permExpensesDelete',
  'expenses.edit': 'permExpensesEdit',
  'expenses.view': 'permExpensesView',
  'fx.manage': 'permFxManage',
  'fx.view': 'permFxView',
  'integrations.manage': 'permIntegrationsManage',
  'integrations.view': 'permIntegrationsView',
  'pnl_labels.manage': 'permPnlLabelsManage',
  'pnl_labels.view': 'permPnlLabelsView',
  'products.edit': 'permProductsEdit',
  'products.view': 'permProductsView',
  'reports.view': 'permReportsView',
  'sales.view': 'permSalesView',
  'simulations.view': 'permSimulationsView',
  'team.manage': 'permTeamManage',
  'team.view': 'permTeamView',
  'workspace_config.view': 'permWorkspaceConfigView',
}

export const PERMISSION_DESC_KEYS: Record<AssignablePermissionKey, ShellStringKey> = {
  'ads.view': 'permAdsViewDesc',
  'alerts.manage': 'permAlertsManageDesc',
  'alerts.view': 'permAlertsViewDesc',
  'channels.view': 'permChannelsViewDesc',
  'expenses.create': 'permExpensesCreateDesc',
  'expenses.delete': 'permExpensesDeleteDesc',
  'expenses.edit': 'permExpensesEditDesc',
  'expenses.view': 'permExpensesViewDesc',
  'fx.manage': 'permFxManageDesc',
  'fx.view': 'permFxViewDesc',
  'integrations.manage': 'permIntegrationsManageDesc',
  'integrations.view': 'permIntegrationsViewDesc',
  'pnl_labels.manage': 'permPnlLabelsManageDesc',
  'pnl_labels.view': 'permPnlLabelsViewDesc',
  'products.edit': 'permProductsEditDesc',
  'products.view': 'permProductsViewDesc',
  'reports.view': 'permReportsViewDesc',
  'sales.view': 'permSalesViewDesc',
  'simulations.view': 'permSimulationsViewDesc',
  'team.manage': 'permTeamManageDesc',
  'team.view': 'permTeamViewDesc',
  'workspace_config.view': 'permWorkspaceConfigViewDesc',
}
