import type { ModuleDefinition } from '@/lib/modules/types'

export const MODULES: readonly ModuleDefinition[] = [
  {
    id: 'products',
    labelKey: 'navProductCatalog',
    path: '/dashboard/products',
    icon: 'products',
    comingSoon: false,
    section: 'analytics',
  },
  {
    id: 'sales',
    labelKey: 'navSales',
    path: '/dashboard/sales',
    icon: 'sales',
    comingSoon: true,
    section: 'analytics',
  },
  {
    id: 'reports',
    labelKey: 'navReports',
    path: '/dashboard/reports',
    icon: 'reports',
    comingSoon: false,
    section: 'analytics',
  },
  {
    id: 'ads',
    labelKey: 'navAds',
    path: '/dashboard/ads',
    icon: 'ads',
    comingSoon: true,
    section: 'analytics',
  },
  {
    id: 'channels',
    labelKey: 'navChannels',
    path: '/dashboard/channels',
    icon: 'channels',
    comingSoon: true,
    section: 'analytics',
  },
  {
    id: 'simulations',
    labelKey: 'navSimulations',
    path: '/dashboard/simulations',
    icon: 'simulations',
    comingSoon: true,
    section: 'analytics',
  },
  {
    id: 'workspace-config',
    labelKey: 'navWorkspaceConfiguration',
    path: '/dashboard/configuration',
    icon: 'config',
    comingSoon: false,
    section: 'config',
  },
  {
    id: 'integrations',
    labelKey: 'navIntegrations',
    path: '/dashboard/integrations',
    icon: 'integrations',
    comingSoon: false,
    section: 'config',
  },
] as const
