#!/usr/bin/env sh
root="$(git rev-parse --show-toplevel)"
# shellcheck disable=SC1090
. "$root/scripts/git/validate-branch-name.sh"
cd "$root" || exit 1
pnpm lint
pnpm run typecheck
VITE_CLERK_PUBLISHABLE_KEY=pk_test_dummy_ci_only pnpm build
